name: STARAYSinc
favicon: null
layout_spectrum: 0.034306259360164404
typography_spectrum: 0.5556708408985287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6324901271145791
  lightness: 0.7096878050360829
  saturation: 0.8176125180907547
  rhythmicContrast: 0.7340980514418334
purpose: []
